### ISSUE TITLE
Problem with dplyr "tbl_df" 

### ISSUE THREAD

**Issue by petestmarie** [ujjwalkarn/xda#3]
Broken

```
iris_df <- dplyr::tbl_df(iris)
xda::numSummary(iris_df)
```

 `tbl_df` returns a data.frame from `df[, var]`, xda should probably use `df[[var]]`

For example

```
for (var in 1:ncol(df)) {
  if (class(df[[var]]) == "numeric" ||
      class(df[[var]]) == "integer") {
    num  <- c(num, names(df[var]))
  } else if (class(df[[var]]) == "factor" ||
             class(df[[var]]) == "character") {
    char  <- c(char, names(df[var]))
  }
}
```

**Comment by jennybc** [comment]
👍 to fixing this package so it can work on a `tbl_df`. I came here because my package `googlesheets` returns `tbl_df` and a user had to use `as.data.frame()` on the resulting data frame to use functions from `xda`.

Side note: you might want to replace the `class(...) == "numeric"` statements throughout this package with calls to `inherits()`. It will be more robust.

**Comment by kissmygritts** [comment]
A simple fix is to use `data.frame` in the function call. `numSummary(data.frame(data))`

**Comment by ujjwalkarn** [comment]
Thanks for flagging, will fix this soon!

**Comment by ujjwalkarn** [comment]
This issue is now fixed.
